#!/usr/bin/env python3
"""Generate an opening book by asking Stockfish, written in the line format the engine loads.

    python3 tools/genbook.py [plies] [root_width] [depth] > /dev/null

Defaults: 12 plies, width 3 near the root, Stockfish depth 12. Writes `book-generated.txt`.

WHY STOCKFISH RATHER THAN A GAME DATABASE

No API, no rate limit, nothing to download — and the decisive reason: a database's win rate
measures how *humans of that population* fare with an opening, which is not our population. This
engine has no mobility term, no king safety and no notion of space; the sharpest, best-scoring
human lines are exactly the ones demanding what it lacks. Choosing openings on someone else's
strengths is the same error as measuring a brick against a clone that shares its blind spot.

Stockfish returns the best move rather than the most played one. If a statistics-based book is
ever wanted, filter it by rating band — that is stage two of the issue this came from.

WHY LINES RATHER THAN ENTRIES

The engine's loader replays lines and merges transpositions by itself, so emitting root-to-leaf
paths keeps the file format identical to the hand-written book and lets the two be concatenated.

WHY THE WIDTH NARROWS AWAY FROM THE ROOT

Diversity is worth most on the first moves: an engine that always opens the same way hands its
opponent free preparation. Depth is worth most afterwards. So the first four plies keep the top
three moves and everything below keeps two, which also stops the tree exploding — the full
width-three tree to twelve plies would be a hundred times larger for openings nobody reaches.

WHY A TRANSPOSITION ENDS THE LINE

When the walk reaches a position already explored, the line stops there rather than repeating the
subtree. Not laziness: the engine's book is keyed by position, so it will find the continuation
under that key anyway. Re-emitting it would only make the file larger.
"""
import collections
import sys

import chess
import chess.engine

STOCKFISH = "/usr/games/stockfish"


def main() -> int:
    plies = int(sys.argv[1]) if len(sys.argv) > 1 else 12
    root_width = int(sys.argv[2]) if len(sys.argv) > 2 else 3
    depth = int(sys.argv[3]) if len(sys.argv) > 3 else 12

    engine = chess.engine.SimpleEngine.popen_uci(STOCKFISH)
    seen: set[str] = set()
    lines: list[str] = []
    calls = 0

    def walk(board: chess.Board, path: list[str]) -> None:
        nonlocal calls
        if len(path) >= plies or board.epd() in seen:
            lines.append(" ".join(path))
            return
        seen.add(board.epd())
        width = root_width if len(path) < 4 else 2
        try:
            infos = engine.analyse(board, chess.engine.Limit(depth=depth), multipv=width)
        except chess.engine.EngineError:
            lines.append(" ".join(path))
            return
        calls += 1
        if calls % 500 == 0:
            print(f"  {calls} calls, {len(lines)} lines", file=sys.stderr, flush=True)
        moves = [i["pv"][0] for i in infos if i.get("pv")][:width]
        if not moves:
            lines.append(" ".join(path))
            return
        for move in moves:
            board.push(move)
            walk(board, path + [move.uci()])
            board.pop()

    walk(chess.Board(), [])
    engine.quit()

    with open("book-generated.txt", "w") as out:
        out.write(f"# Generated by tools/genbook.py: {plies} plies, root width {root_width}, ")
        out.write(f"Stockfish depth {depth}.\n")
        out.write("# Regenerate rather than edit — a hand edit here is invisible to review.\n")
        for line in lines:
            if line:
                out.write(line + "\n")
    print(f"{calls} Stockfish calls -> {len(lines)} lines, {len(seen)} positions", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
